/**
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.ide;

import polytech.dsl.spaceteam.spaml.ide.AbstractSpamlIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SpamlIdeModule extends AbstractSpamlIdeModule {
}
