/**
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import polytech.dsl.spaceteam.spaml.SpamlRuntimeModule;
import polytech.dsl.spaceteam.spaml.SpamlStandaloneSetup;
import polytech.dsl.spaceteam.spaml.ide.SpamlIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SpamlIdeSetup extends SpamlStandaloneSetup {
  @Override
  public Injector createInjector() {
    SpamlRuntimeModule _spamlRuntimeModule = new SpamlRuntimeModule();
    SpamlIdeModule _spamlIdeModule = new SpamlIdeModule();
    return Guice.createInjector(Modules2.mixin(_spamlRuntimeModule, _spamlIdeModule));
  }
}
