/*
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSpamlScopeProvider extends DelegatingScopeProvider {
}
