/*
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpamlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("polytech/dsl/spaceteam/spaml/parser/antlr/internal/InternalSpaml.tokens");
	}
}
