/*
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import polytech.dsl.spaceteam.spaml.parser.antlr.internal.InternalSpamlParser;
import polytech.dsl.spaceteam.spaml.services.SpamlGrammarAccess;

public class SpamlParser extends AbstractAntlrParser {

	@Inject
	private SpamlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSpamlParser createParser(XtextTokenStream stream) {
		return new InternalSpamlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public SpamlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SpamlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
