/*
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SpamlStandaloneSetup extends SpamlStandaloneSetupGenerated {

	def static void doSetup() {
		new SpamlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
