/*
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SpamlRuntimeModule extends AbstractSpamlRuntimeModule {
}
