/**
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.generator;

import arduinoML.Actuator;
import arduinoML.OPERATION;
import arduinoML.PluggedElement;
import arduinoML.Program;
import arduinoML.SIGNAL;
import arduinoML.Sensor;
import com.google.common.collect.Iterables;
import io.github.mosser.arduinoml.kernel.App;
import io.github.mosser.arduinoml.kernel.behavioral.Action;
import io.github.mosser.arduinoml.kernel.behavioral.State;
import io.github.mosser.arduinoml.kernel.behavioral.Transition;
import io.github.mosser.arduinoml.kernel.behavioral.TransitionHandler;
import io.github.mosser.arduinoml.kernel.generator.ToWiring;
import io.github.mosser.arduinoml.kernel.structural.Brick;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class SpamlGenerator extends AbstractGenerator {
  @Inject
  @Extension
  private IQualifiedNameProvider _iQualifiedNameProvider;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    Iterable<Program> _filter = Iterables.<Program>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Program.class);
    for (final Program program : _filter) {
      QualifiedName _fullyQualifiedName = this._iQualifiedNameProvider.getFullyQualifiedName(program);
      String _plus = (_fullyQualifiedName + ".ino");
      fsa.generateFile(_plus, 
        this.compile(program));
    }
  }
  
  private String compile(final Program program) {
    final App app = new App();
    app.setBricks(this.constructPluggedElements(program));
    app.setInitial(this.constructInitialState(program));
    app.setStates(this.constructStates(program));
    final ToWiring toWiring = new ToWiring();
    toWiring.visit(app);
    return toWiring.getResult().toString();
  }
  
  private List<Brick> constructPluggedElements(final Program program) {
    final ArrayList<Brick> bricks = new ArrayList<Brick>();
    EList<PluggedElement> _pluggedElements = program.getPluggedElements();
    for (final PluggedElement pe : _pluggedElements) {
      bricks.add(this.convertSpamlBrickToMosserBrick(pe));
    }
    return bricks;
  }
  
  private Brick convertSpamlBrickToMosserBrick(final PluggedElement pe) {
    if ((pe instanceof Sensor)) {
      return this.convertSpamlSensorToMosser(((Sensor)pe));
    } else {
      if ((pe instanceof Actuator)) {
        return this.convertSpamlActuatorToMosser(((Actuator)pe));
      }
    }
    return null;
  }
  
  private io.github.mosser.arduinoml.kernel.structural.Sensor convertSpamlSensorToMosser(final Sensor pe) {
    final io.github.mosser.arduinoml.kernel.structural.Sensor sensor = new io.github.mosser.arduinoml.kernel.structural.Sensor();
    sensor.setName(pe.getName());
    sensor.setPin(pe.getPin());
    return sensor;
  }
  
  private io.github.mosser.arduinoml.kernel.structural.Actuator convertSpamlActuatorToMosser(final Actuator pe) {
    final io.github.mosser.arduinoml.kernel.structural.Actuator actuator = new io.github.mosser.arduinoml.kernel.structural.Actuator();
    actuator.setName(pe.getName());
    actuator.setPin(pe.getPin());
    return actuator;
  }
  
  private State constructInitialState(final Program program) {
    final State initialState = new State();
    initialState.setName(program.getInitialState().getName());
    initialState.setTransition(this.getTransitionFromState(program.getInitialState()));
    initialState.setActions(this.getActionsFromState(program.getInitialState()));
    return initialState;
  }
  
  private TransitionHandler convertTransitionHandlerToMosser(final arduinoML.TransitionHandler transitionHandler) {
    final TransitionHandler handler = new TransitionHandler();
    SIGNAL _value = transitionHandler.getValue();
    boolean _tripleEquals = (_value == SIGNAL.HIGH);
    if (_tripleEquals) {
      handler.setValue(io.github.mosser.arduinoml.kernel.structural.SIGNAL.HIGH);
    } else {
      handler.setValue(io.github.mosser.arduinoml.kernel.structural.SIGNAL.LOW);
    }
    handler.setSensor(this.convertSpamlSensorToMosser(transitionHandler.getSensor()));
    return handler;
  }
  
  private Transition getTransitionFromState(final arduinoML.State state) {
    final Transition transition = new Transition();
    final ArrayList<TransitionHandler> handlers = new ArrayList<TransitionHandler>();
    EList<arduinoML.TransitionHandler> _handlers = state.getTransition().getHandlers();
    for (final arduinoML.TransitionHandler t : _handlers) {
      handlers.add(this.convertTransitionHandlerToMosser(t));
    }
    transition.setHandlers(handlers);
    OPERATION _operation = state.getTransition().getOperation();
    boolean _tripleEquals = (_operation == OPERATION.AND);
    if (_tripleEquals) {
      transition.setOperation(io.github.mosser.arduinoml.kernel.structural.OPERATION.AND);
    } else {
      transition.setOperation(io.github.mosser.arduinoml.kernel.structural.OPERATION.OR);
    }
    final State nextState = new State();
    nextState.setName(state.getTransition().getNext().getName());
    transition.setNext(nextState);
    return transition;
  }
  
  private List<Action> getActionsFromState(final arduinoML.State state) {
    final ArrayList<Action> actions = new ArrayList<Action>();
    EList<arduinoML.Action> _actions = state.getActions();
    for (final arduinoML.Action a : _actions) {
      {
        final Action action = new Action();
        action.setActuator(this.convertSpamlActuatorToMosser(a.getActuator()));
        SIGNAL _value = a.getValue();
        boolean _tripleEquals = (_value == SIGNAL.HIGH);
        if (_tripleEquals) {
          action.setValue(io.github.mosser.arduinoml.kernel.structural.SIGNAL.HIGH);
        } else {
          action.setValue(io.github.mosser.arduinoml.kernel.structural.SIGNAL.LOW);
        }
        actions.add(action);
      }
    }
    return actions;
  }
  
  private List<State> constructStates(final Program program) {
    final ArrayList<State> states = new ArrayList<State>();
    EList<arduinoML.State> _states = program.getStates();
    for (final arduinoML.State s : _states) {
      {
        final State state = new State();
        state.setName(s.getName());
        state.setTransition(this.getTransitionFromState(s));
        state.setActions(this.getActionsFromState(s));
        states.add(state);
      }
    }
    return states;
  }
}
