/*
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import polytech.dsl.spaceteam.spaml.ui.internal.SpamlActivator;

public class SpamlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpamlActivator.getInstance().getInjector("polytech.dsl.spaceteam.spaml.Spaml");
	}

}
