/**
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml;

import polytech.dsl.spaceteam.spaml.AbstractSpamlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SpamlRuntimeModule extends AbstractSpamlRuntimeModule {
}
