/**
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml;

import polytech.dsl.spaceteam.spaml.SpamlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SpamlStandaloneSetup extends SpamlStandaloneSetupGenerated {
  public static void doSetup() {
    new SpamlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
