/**
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.scoping;

import polytech.dsl.spaceteam.spaml.scoping.AbstractSpamlScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SpamlScopeProvider extends AbstractSpamlScopeProvider {
}
