/**
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import polytech.dsl.spaceteam.spaml.ui.AbstractSpamlUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SpamlUiModule extends AbstractSpamlUiModule {
  public SpamlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
