/*
 * generated by Xtext 2.14.0
 */
package polytech.dsl.spaceteam.spaml.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import polytech.dsl.spaceteam.spaml.ui.internal.SpamlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpamlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SpamlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SpamlActivator activator = SpamlActivator.getInstance();
		return activator != null ? activator.getInjector(SpamlActivator.POLYTECH_DSL_SPACETEAM_SPAML_SPAML) : null;
	}

}
